[package]
name = "blockious-local-storage-manager"
version = "0.1.0"
authors = ["Mihir Luthra <1999mihir.luthra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
